[34m[1mwandb[39m[22m: [33mWARNING[39m The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
Traceback (most recent call last):
  File "main.py", line 63, in <module>
    trainer.train()
  File "/home/grad-min/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/home/grad-min/.local/lib/python3.8/site-packages/transformers/trainer.py", line 2147, in _inner_training_loop
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
  File "/home/grad-min/.local/lib/python3.8/site-packages/transformers/trainer_callback.py", line 454, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "/home/grad-min/.local/lib/python3.8/site-packages/transformers/trainer_callback.py", line 498, in call_event
    result = getattr(callback, event)(
  File "/home/grad-min/.local/lib/python3.8/site-packages/transformers/integrations/integration_utils.py", line 842, in on_train_begin
    self.setup(args, state, model, **kwargs)
  File "/home/grad-min/.local/lib/python3.8/site-packages/transformers/integrations/integration_utils.py", line 815, in setup
    model.save_pretrained(temp_dir)
  File "/home/grad-min/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CodeBertModel' object has no attribute 'save_pretrained'
Traceback (most recent call last):
  File "main.py", line 63, in <module>
    trainer.train()
  File "/home/grad-min/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/home/grad-min/.local/lib/python3.8/site-packages/transformers/trainer.py", line 2147, in _inner_training_loop
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
  File "/home/grad-min/.local/lib/python3.8/site-packages/transformers/trainer_callback.py", line 454, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "/home/grad-min/.local/lib/python3.8/site-packages/transformers/trainer_callback.py", line 498, in call_event
    result = getattr(callback, event)(
  File "/home/grad-min/.local/lib/python3.8/site-packages/transformers/integrations/integration_utils.py", line 842, in on_train_begin
    self.setup(args, state, model, **kwargs)
  File "/home/grad-min/.local/lib/python3.8/site-packages/transformers/integrations/integration_utils.py", line 815, in setup
    model.save_pretrained(temp_dir)
  File "/home/grad-min/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CodeBertModel' object has no attribute 'save_pretrained'